[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "22"

[build]
  publish = ".output/public"
  command = "npm install --prefer-offline && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
