[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "npm install --prefer-offline && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
